#!/usr/bin/env zsh
TEMP_PATH=~/.bootstrap_laptop

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

echo "Setup temp area for downloads ..."
  successfully mkdir $TEMP_PATH

echo "Download dotfiles ..."
  successfully git clone https://github.com/bsodmike/dotfiles.git $TEMP_PATH/dotfiles

echo "Set Git Config ..."
  successfully cp $TEMP_PATH/dotfiles/git/.gitconfig ~/

echo "Installing OH MY ZSHELL! ..."
  successfully curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
  successfully cp $TEMP_PATH/dotfiles/oh-my-zsh/.zshrc ~/
  successfully cp $TEMP_PATH/dotfiles/oh-my-zsh/themes/bsodmike.zsh-theme ~/.oh-my-zsh/themes/bsodmike.zsh-theme

echo "Set Solarized Theme for Terminal ..."
  successfully curl https://raw.github.com/altercation/solarized/master/osx-terminal.app-colors-solarized/Solarized%20Dark%20ansi.terminal > $TEMP_PATH/solarized_dark_ansi.terminal
  successfully open $TEMP_PATH/solarized_dark_ansi.terminal

echo "Installing JANUS ..."
  successfully curl -Lo- https://bit.ly/janus-bootstrap | zsh
  successfully git clone https://github.com/bsodmike/janus.git ~/.janus
  successfully cd ~/.janus && git submodule update --init
  successfully cp $TEMP_PATH/dotfiles/vim/.vimrc.after ~/.vimrc.after
  successfully cp $TEMP_PATH/dotfiles/vim/.vimrc.before ~/.vimrc.before

echo "Fixing permissions ..."
  successfully sudo mkdir -p /usr/local
  successfully sudo chown -R `whoami` /usr/local

echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
  successfully brew update

echo "Installing GNU Compiler Collection and dependencies ..."
  successfully brew tap homebrew/dupes
  successfully brew install autoconf automake apple-gcc42

echo "Installing system libraries recommended for Ruby ..."
  successfully brew install gdbm libffi libksba libyaml

echo "Installing Postgres, a good open source relational database ..."
  successfully brew install postgres --no-python
  successfully initdb /usr/local/var/postgres -E utf8

echo "Installing Redis, a good key-value database ..."
  successfully brew install redis

echo "Installing The Silver Searcher (better than ack or grep) for searching the contents of files ..."
  successfully brew install the_silver_searcher

echo "Installing ctags, for indexing files for vim tab completion of methods, classes, variables ..."
  successfully brew install ctags

echo "Installing tmux, for saving project state and switching between projects ..."
  successfully brew install tmux

echo "Installing reattach-to-user-namespace, for copy-paste and RubyMotion compatibility with tmux ..."
  successfully brew install reattach-to-user-namespace

echo "Installing ImageMagick, for cropping and re-sizing images ..."
  successfully brew install imagemagick

echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
  successfully brew install qt

echo "Installing watch, used to execute a program periodically and show the output ..."
  successfully brew install watch

echo "Installing rbenv for changing Ruby versions ..."
  successfully brew install rbenv
  successfully echo 'eval "$(rbenv init -)"' >> ~/.zshrc
  successfully echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.zshrc
  successfully source ~/.zshrc

echo "Installing rbenv-gem-rehash so the shell automatically picks up binaries after installing gems with binaries..."
  successfully brew install rbenv-gem-rehash

echo "Installing ruby-build for installing Rubies ..."
  successfully brew install ruby-build

echo "Installing Ruby 1.9.3-p392 ..."
  successfully rbenv install 1.9.3-p392

echo "Setting Ruby 1.9.3-p392 as global default Ruby ..."
  successfully rbenv global 1.9.3-p392
  successfully rbenv shell 1.9.3-p392

echo "Update to latest Rubygems version ..."
  successfully gem update --system

echo "Installing critical Ruby gems for Rails development ..."
  successfully gem install bundler foreman rails thin pry --no-document

echo "Install Python (Framework), pip, virtualenv, and virtualenvwrapper ..."
  successfully brew install python --framework
  successfully easy_install pip
  successfully pip install virtualenv
  successfully pip install virtualenvwrapper
  successfully mkdir $HOME/.virtualenvs
  successfully echo 'export PATH="/usr/local/share/python:$PATH"' >> ~/.zshrc
  successfully echo 'export WORKON_HOME=$HOME/.virtualenvs' >> ~/.zshrc
  successfully echo 'source /usr/local/share/python/virtualenvwrapper.sh' >> ~/.zshrc

echo "Install Node and npm ..."
  successfully brew install node
  successfully curl https://npmjs.org/install.sh | sh

echo "Your shell will now restart in order for changes to apply."
  exec $SHELL -l
